%YAML 1.1
---
# Configs for all Edge services
# this file should be located at /boot/signage/config.yml

###########################################################
####            Orchestration and Image Feed           ####
###########################################################
cam_stream_address    : 192.168.1.168/usecondstream
cam_protocol          : rtsp://

cam_location_name     : signage-analysis-demo
cam_name              : signage-camera-1
logfile_path          : /home/pi/signage.log
logfile_maxbytes      : 375000000


# Enable/Disable Services
serve_ads             : True
gender_classification : True
data_report           : True

# Interfaces
data_address_port     : 127.0.0.1:5000
data_protocol         : http://

gender classification :
    - localhost # server
    - 18862     # port

ad server             :
    - localhost # server
    - 18861     # port


###########################################################
####                     Ad Server                     ####
###########################################################
# these should become a separate configuration e.g. /opt/signage/ads.yml
ad_server       :
  source_camera_inset : True
  debug_positions     : False
  video_uri : /opt/signage/videos/multi_ads.mov



